In [2]:
import numpy as np
from numpy import random

In [9]:
v1 = np.zeros(10)
print(v1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
v2 = np.zeros(10)
v2[4] = 1
print(v2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
v3 = np.random.rand(20)
print(v3)
print(np.argwhere(v3))

[0.98146376 0.55435988 0.3649751  0.55148689 0.41133253 0.03048331
 0.58415629 0.20314062 0.13307239 0.24018192 0.1828687  0.79217351
 0.48443464 0.98312019 0.74348372 0.43161489 0.75730156 0.17977074
 0.50786798 0.92549847]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [20]:
v4 = np.random.rand(3, 3, 3)
print(v3)

[0.98146376 0.55435988 0.3649751  0.55148689 0.41133253 0.03048331
 0.58415629 0.20314062 0.13307239 0.24018192 0.1828687  0.79217351
 0.48443464 0.98312019 0.74348372 0.43161489 0.75730156 0.17977074
 0.50786798 0.92549847]


In [21]:
v5 = np.random.rand(10)
print(v5)
print(np.average(v5))

[0.53804868 0.68700423 0.78431757 0.83234025 0.49072087 0.76118627
 0.8631665  0.65244217 0.78792585 0.17603132]
0.6573183713012366


In [32]:
v6_1 = np.random.randint(10, size=[5, 3])
v6_2 = np.random.randint(10, size =[3, 2])
print(v6_1)
print(v6_2)
print(np.matmul(v6_1, v6_2))


[[2 8 8]
 [5 4 1]
 [6 8 8]
 [8 5 1]
 [2 7 5]]
[[6 4]
 [1 3]
 [0 3]]
[[20 56]
 [34 35]
 [44 72]
 [53 50]
 [19 44]]


In [34]:
v7_1 = np.random.randint(10, size =[4, 4])
v7_2 = np.random.randint(10, size =[4, 4])
v7 = np.matmul(v7_1, v7_2)
print(v7_1)
print(v7_2)
print(v7)
print(np.diagonal(v7))


[[7 6 8 0]
 [6 1 0 4]
 [9 2 3 9]
 [5 8 5 8]]
[[0 9 3 2]
 [9 9 9 4]
 [2 5 4 0]
 [7 2 1 6]]
[[ 70 157 107  38]
 [ 37  71  31  40]
 [ 87 132  66  80]
 [138 158 115  90]]
[70 71 66 90]


In [39]:
v8 = np.random.randint(50, size = 20)
print(v8)
v8[v8 == v8.max()] = 0
print(v8)

[11  4 36 29 16 40 29  8  5 45 29 37 32 11 38  0 32 18 27 10]
[11  4 36 29 16 40 29  8  5  0 29 37 32 11 38  0 32 18 27 10]


In [44]:
v9 = np.random.randint(10, size = 20)
print(v9)
print(np.unique(v9))

[1 4 6 6 6 4 2 6 9 3 2 9 8 4 3 4 4 0 4 4]
[0 1 2 3 4 6 8 9]


In [47]:
v10 = np.random.randint(10, size = [4, 4])
print(v10)
v10 = v10 - np.average(v10)
print(v10)

[[1 3 7 3]
 [0 5 8 9]
 [2 8 1 7]
 [5 4 6 4]]
[[-3.5625 -1.5625  2.4375 -1.5625]
 [-4.5625  0.4375  3.4375  4.4375]
 [-2.5625  3.4375 -3.5625  2.4375]
 [ 0.4375 -0.5625  1.4375 -0.5625]]


In [50]:
v11 = np.random.randint(10, size = [4, 4])
print(v11)
v11[[0, 1]] = v11[[1, 0]]
print(v11)

[[5 0 5 5]
 [8 8 4 1]
 [6 3 5 7]
 [8 5 1 5]]
[[8 8 4 1]
 [5 0 5 5]
 [6 3 5 7]
 [8 5 1 5]]


In [7]:
v12 = np.random.randint(10, size=20)
print(v12)
np.sort(v12)[-3::]


[1 1 1 3 9 5 8 4 5 5 4 2 7 9 7 6 2 4 0 5]


array([8, 9, 9])

In [16]:
v13 = np.random.randint(1, 10, size = [5, 5])
print(v13)
np.sum(v13, axis = 1)

[[7 4 4 2 2]
 [2 9 7 3 7]
 [7 5 3 8 5]
 [6 8 2 3 4]
 [3 8 1 2 5]]


array([19, 28, 28, 23, 19])

In [24]:
v14 = np.random.rand(10) *2-1
print(v14)
v14[v14<0]=-1
v14[v14>0]=1
print(v14)

[ 0.67546977  0.22119767 -0.49291321  0.10748023 -0.82701549 -0.80663366
  0.46900862  0.77013806  0.71836513 -0.061042  ]
[ 1.  1. -1.  1. -1. -1.  1.  1.  1. -1.]


In [30]:
v15 = np.random.randint(1, 100, size=12)
print(v15)
v15_1 = np.array_split(v15, 3)
print(np.sum(v15_1, axis=1))

[39 67 80 57  5 14 82 70 97 36 47 54]
[243 171 234]
